<a href="https://colab.research.google.com/github/Dilan-D-S/Inteligencia_Artificial_Est/blob/main/Taller1/Ejemplos1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller de Numpy
**Ejercicios**
Autor: Dilan Delgado

fecha:16/04/2026

## **Modulo 1**
----------
----------

In [ ]:
numeros = [10,20,30,40,50]
mixta = [1,'Texto',3.14, True]
vacia = []
de_rango =list(range(1,11))


Acceso por Indices

In [ ]:
print(numeros)

[10, 20, 30, 40, 50]


Slicing [inicio : fin : paso]

In [ ]:
print(numeros[1:4]) # [20, 30, 40] índices 1,2,3
print(numeros[:3])  # [10, 20, 30] desde el inicio hasta índice 2
print(numeros[3:])  # [30, 40, 50] desde índice 2 hasta el final
print(numeros[::2]) # [10, 30, 50] cada 2 elementos
print(numeros[::-1]) # [50, 40, 30, 20, 10] invertida

[20, 30, 40]
[10, 20, 30]
[40, 50]
[10, 30, 50]
[50, 40, 30, 20, 10]


**Metodos Principales**

In [ ]:
numeros.append(60)  # agrega al final → O(1
numeros.insert(2, 99)  # inserta en posición 2 → O(n)
numeros.remove(99)  # elimina primera ocurrencia
numeros.pop()
print(len(numeros),numeros)


[10, 20, 30, 40, 50, 60]

Las operaciones en colab no son idempotentes

**List Comprehensions**

In [ ]:
cuadrados = [x**2 for x in range (1, 8)]
pares = [x for x in range(1, 21) if x % 2 == 0]

print(cuadrados)
print(pares)


[1, 4, 9, 16, 25, 36, 49]


**Comprehensions anidada(matriz)**

In [ ]:
tabla = [[i * j for j in range(1, 4)] for i in range(1, 4)]
print(tabla)

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]


**transformación de tipo**

In [ ]:
palabras = ['hola', 'MUNDO', 'Python']
minusculas = [w.lower() for w in palabras]

Una tupla es una secuencia ordenada **inmutable** no se puede cambiar

***Consultar que son las tablas hash***

# **Tuplas**

In [ ]:
coordenada = (3.5, -1.2)  # tupla de 2 elementos
dimensiones = (28, 28, 3) # alto, ancho, canales (imagen RGB)
unitaria = (42,)          # IMPORTANTE: la coma crea la tupla
no_tupla = (42)           # esto es sólo el entero 42

print("coordenada: ",coordenada,"\ndimensiones: ",dimensiones)
print("Unitaria: ",unitaria,"\nno tupla: ",no_tupla)

coordenada:  (3.5, -1.2) 
dimensiones:  (28, 28, 3)
Unitaria:  (42,) 
no tupla:  42


**Acceso**

In [ ]:
print(dimensiones[0]) # 28
print(dimensiones[-1]) # 3

28
3


**Desempaquetado**

In [ ]:
x, y = coordenada # x = 3.5, y = -1.2
alto, ancho, profundidad = dimensiones
print(x,y,alto,profundidad)

3.5 -1.2 28 3


**Las tuplas son inmutables**

In [ ]:
dimensiones[0] = 64  #Esto da ERROR

NameError: name 'dimensiones' is not defined

# **Diccionario**



---

**Creacion**

In [ ]:
estudiante = {
'nombre': 'María',
'edad': 22,
'notas': [8.5, 9.0, 7.5],
'activo': True
}
print(estudiante)

{'nombre': 'María', 'edad': 22, 'notas': [8.5, 9.0, 7.5], 'activo': True}


**Acceso**

In [ ]:
print(estudiante['nombre'])
print(estudiante.get('carrera', 'N/A'))

María
N/A


**Modificacion**

In [ ]:
estudiante['edad'] = 23     # modifica valor existente
estudiante['semestre'] = 6  # agrega nueva clave

**Iteracion**

In [ ]:
for clave, valor in estudiante.items():
  print(f'{clave:12s} → {valor}')

nombre       → María
edad         → 23
notas        → [8.5, 9.0, 7.5]
activo       → True
semestre     → 6


**Dict comprehension**

In [ ]:
cubos = {x: x**3 for x in range(1, 6)}
print(cubos)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}


**Otros Metodos**

In [ ]:
elementos= list(estudiante.values())
print(elementos, type(elementos))

# **Funciones**

**Funcion basica**

In [ ]:
def saludar(nombre):
  return f'Hola, {nombre}!'

saludar("Dilan")

'Hola, Dilan!'

**Con parametros por defecto**

In [ ]:
def potencia(base, exponente=2):
  '''Eleva base a exponente. Por defecto calcula el cuadrado.'''
  return base ** exponente

print(potencia(5))
print(potencia(2,3))

25
8


**Retorno Multiple**

In [ ]:
def min_max(lista):
  return min(lista), max(lista)

minimo, maximo = min_max([3,1,7,2,5])

print("Minimo: ",minimo,"\nMaximo: ",maximo)

Minimo:  1 
Maximo:  7


**Lambda — función anónima**

In [ ]:
doble = lambda x: x * 2
print(doble(8))

16


**Argumento de Orden Superior**

In [ ]:
nums = [5, 2, 8, 1, 9, 3]
ordenados = sorted(nums, key=lambda x: -x)

print(ordenados) #Orden Descendente

[9, 8, 5, 3, 2, 1]


**map y filter**

In [ ]:
cuadrados1 = list(map(lambda x: x**2, nums))
mayores = list(filter(lambda x: x > 4, nums))

print("Cuadrados: ",cuadrados1,"\nMayores: ",mayores)

Cuadrados:  [25, 4, 64, 1, 81, 9] 
Mayores:  [5, 8, 9]


##**Modulo 2**
-----------
-----------

**Array 1-D (vector)**

In [2]:
import numpy as np

v = np.array([10, 20, 30, 40, 50])
print(v)
print(type(v))
print(v.dtype)


[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


**Array 2-D (Matriz)**

In [3]:
M = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Upcasting automático

In [4]:
mix = np.array([1, 2, 3.0]) # int + float → float64
print(mix.dtype)

float64


**Forzar tipo de dato**

In [7]:
float32 = np.array([1, 2, 3], dtype=np.float32)
booleano = np.array([0, 1, 0, 1], dtype=bool)
print(float32.dtype)
print(booleano)

float32
[False  True False  True]


**Arrays de ceros y unos**

In [13]:
ceros = np.zeros((3, 4))
unos = np.ones((2, 5))
print(ceros.shape)
print(ceros)
print(unos.shape)

(3, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 5)


**Identidad**

In [14]:
I = np.eye(4)
print(I) #Diagonal 1

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**arange vs linspace**

In [17]:
#arange: define el PASO
a = np.arange(0, 10, 2)

linspace: define la CANTIDAD de puntos


In [16]:
b = np.linspace(0, 1, 5)
print('arange: ', a)
print('linspace:', b)


arange:  [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


**Aleatorios**

In [20]:
np.random.seed(42) # semilla fija → reproducible
uniforme = np.random.rand(3, 4) # valores entre [0,1]
normal = np.random.randn(3, 4) # distribución normal (μ=0, σ=1)
enteros = np.random.randint(1, 10, size=(3, 3)) # enteros en [1, 10)
print("uniforme: ",uniforme)
print("normal: ",normal)
print("enteros: ",enteros)


uniforme:  [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
normal:  [[-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]
enteros:  [[3 7 4]
 [9 3 5]
 [3 7 5]]


***Atributos del ndarray***

In [22]:
A = np.random.randint(0, 100, size=(4, 3, 2))
print('shape: ', A.shape)
print('ndim: ', A.ndim)
print('size: ', A.size)
print('dtype: ', A.dtype)
print('itemsize: ', A.itemsize)
print('nbytes: ', A.nbytes)

shape:  (4, 3, 2)
ndim:  3
size:  24
dtype:  int64
itemsize:  8
nbytes:  192


**Diferencia entre shape de vector y matriz**

In [24]:
v = np.array([1, 2, 3, 4, 5])
M = np.array([[1, 2, 3, 4, 5]])
print("Vector de elementos: ",v.shape)
print("Matriz de tamaño: ",M.shape)

Vector de elementos:  (5,)
Matriz de tamaño:  (1, 5)


##**Modulo 3**
-----------
-----------

***Indexing — Acceso a Elementos***

In [25]:
M = np.array([[10, 20, 30],
[40, 50, 60],
[70, 80, 90]])


**Acceso a elementos individuales**

In [26]:
print(M[0, 0]) #fila 0, columna 0
print(M[1, 2]) #fila 1, columna 2
print(M[-1, -1]) #ultima fila ,ultima columna 0

10
60
90


**Acceso a filas y columnas completas**

In [27]:
print(M[0, :]) #fila 0 completa
print(M[:, 1]) #columna 1 completa
print(M[-1, :]) #última fila

[10 20 30]
[20 50 80]
[70 80 90]


**Tensor 3-D**

In [29]:
T = np.arange(24).reshape(2, 3, 4) # 2 'páginas', 3 filas, 4 columnas
print(T[0]) # primera página
print(T[1, 2, 3]) # página 1, fila 2, columna 3
print(T[:, 0, :]) # primera fila de TODAS las páginas

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
23
[[ 0  1  2  3]
 [12 13 14 15]]


***Slicing — Selección de Subconjuntos***

In [30]:
A = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])


**Slicing básico**

In [31]:
sub = A[0:2, 1:3]
print(sub)

[[2 3]
 [6 7]]


**Omitir índices**

In [32]:
print(A[:2, :])
print(A[1:, 2:])

[[1 2 3 4]
 [5 6 7 8]]
[[ 7  8]
 [11 12]]


**Con paso**

In [33]:
print(A[::2, ::2])

[[ 1  3]
 [ 9 11]]


**Vista vs. Copia**

In [34]:
vista = A[0, :] # es una vista
copia = A[0, :].copy() # es una copia independiente
vista[0] = 999 # modifica A también!
copia[0] = 888 # NO modifica A
print(A[0, :]) #vista modificó el original
print(np.shares_memory(A, vista)) # True
print(np.shares_memory(A, copia)) # False


[999   2   3   4]
True
False


***Indexación Booleana***

In [35]:
datos = np.array([[5, 12, 3, 18],
[7, 2, 15, 9],
[11, 6, 20, 1]])

**Crear máscara booleana**

In [36]:
mascara = datos > 10
print(mascara)

[[False  True False  True]
 [False False  True False]
 [ True False  True False]]


**Aplicar máscara (filtro)**

In [37]:
mayores = datos[mascara]
print(mayores)

[12 18 15 11 20]


**Combinación de condiciones**

In [38]:
rango = datos[(datos >= 5) & (datos <= 15)]
print(rango)

[ 5 12  7 15  9 11  6]


**Modificar elementos con máscara**

In [39]:
copia = datos.copy()
copia[copia < 5] = 0
print(copia)

[[ 5 12  0 18]
 [ 7  0 15  9]
 [11  6 20  0]]


**np.where — condicional vectorizado**

In [40]:
resultado = np.where(datos > 10, datos, 0)
print(resultado)


[[ 0 12  0 18]
 [ 0  0 15  0]
 [11  0 20  0]]


***Fancy Indexing***

In [41]:
M = np.array([[10, 11, 12],
[20, 21, 22],
[30, 31, 32],
[40, 41, 42]])


**Selección de filas por índice**

In [42]:
indices = [0, 2, 3]
print(M[indices])

[[10 11 12]
 [30 31 32]
 [40 41 42]]


**Selección en orden arbitrario (incluso repetido)**

In [43]:
print(M[[3, 1, 3, 0]]) # fila 3, luego 1, luego 3 otra vez, luego 0

[[40 41 42]
 [20 21 22]
 [40 41 42]
 [10 11 12]]


**Combinación con slicing**

In [44]:
print(M[[0, 2], 1:])  # filas 0 y 2, columnas desde la 1

[[11 12]
 [31 32]]


**Fancy indexing de columnas**

In [45]:
cols = [2, 0]
print(M[:, cols])

[[12 10]
 [22 20]
 [32 30]
 [42 40]]


**Es siempre COPIA**

In [47]:
copia = M[[0, 1]]
copia[0, 0] = 999
print(M[0, 0])
print(copia[0, 0])

10
999


***Reshape — Cambio de Forma***

In [48]:
v = np.arange(12)

**Reshape básico**

In [49]:
M2x6 = v.reshape(2, 6)
M3x4 = v.reshape(3, 4)
M4x3 = v.reshape(4, 3)
M2x2x3= v.reshape(2, 2, 3)

print("M2x6: ",M2x6)
print("M3x4: ",M3x4)
print("M4x3: ",M4x3)
print("M2x2x3: ",M2x2x3)

M2x6:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
M3x4:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
M4x3:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
M2x2x3:  [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


**Uso de -1 (dimensión automática)**

In [50]:
auto = v.reshape(-1, 3)
print(auto.shape)
auto2 = v.reshape(2, -1)
print(auto2.shape)

(4, 3)
(2, 6)


**flatten vs ravel**

In [51]:
flat = M.flatten()
rav = M.ravel()
flat[0] = 999
print(M[0, 0])
rav[0] = 777
print(M[0, 0])

10
777


**Agregar dimensiones**

In [52]:
v1d = np.array([1, 2, 3, 4])
col = v1d.reshape(-1, 1)
fil = v1d.reshape(1, -1)
print(col.shape, fil.shape)


(4, 1) (1, 4)


## **Modulo 4**
-----------
-----------

In [54]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print("a:", a)
print("b: ", b)

a: [1 2 3 4 5]
b:  [10 20 30 40 50]


**Operaciones aritméticas básicas**

In [56]:
print("suma: ",a + b)
print("resta: ",b - a)
print("multiplicacion: ",a * b)
print("division: ",b / a)
print("potencia: ",a ** 2)
print("division entera:",b // 3)
print("modulo: ",b % 3)

suma:  [11 22 33 44 55]
resta:  [ 9 18 27 36 45]
multiplicacion:  [ 10  40  90 160 250]
division:  [10. 10. 10. 10. 10.]
potencia:  [ 1  4  9 16 25]
division entera: [ 3  6 10 13 16]
modulo:  [1 2 0 1 2]


**Operaciones con escalar (scalar broadcasting)**

In [57]:
print(a * 3)
print(a + 100)
print(a > 2)

[ 3  6  9 12 15]
[101 102 103 104 105]
[False False  True  True  True]


**Matrices**

In [58]:
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
print(M + N)
print(M * N)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


***Broadcasting***

**Escalar + vector (caso más simple)**

In [59]:
v = np.array([1, 2, 3, 4])
print(v + 10)

[11 12 13 14]


**Vector + matriz**

In [60]:
M = np.ones((3, 4))
v = np.array([10, 20, 30, 40])
print(M + v)


[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


**Columna + fila**

In [61]:
col = np.array([[1], [2], [3]])
fil = np.array([10, 20, 30, 40])
suma = col + fil
print(suma)


[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


**Normalización por columna (uso común en datos)**

In [62]:
datos = np.random.randint(1, 100, (5, 3))
maximos = datos.max(axis=0)
norm = datos / maximos
print(norm.round(2))

[[0.9  1.   0.6 ]
 [0.27 0.32 1.  ]
 [0.67 0.5  0.33]
 [0.17 0.55 0.73]
 [1.   0.87 0.1 ]]


**Verificar compatibilidad**

In [68]:
try:
  err = np.ones((3,4)) + np.ones(3)
except ValueError as e:
  print('Error:', e)

Error: operands could not be broadcast together with shapes (3,4) (3,) 


***Funciones Universales (ufuncs)***

In [69]:
v = np.array([-4.5, -1.0, 0.0, 2.5, 9.0])


**Funciones básicas**

In [70]:
print(np.abs(v))
print(np.sqrt(np.abs(v))) # raíz cuadrada (abs para evitar NaN)
print(np.square(v))
print(np.floor(v)) # redondeo hacia abajo
print(np.ceil(v)) # redondeo hacia arriba

[4.5 1.  0.  2.5 9. ]
[2.12132034 1.         0.         1.58113883 3.        ]
[20.25  1.    0.    6.25 81.  ]
[-5. -1.  0.  2.  9.]
[-4. -1.  0.  3.  9.]


**Exponencial y logaritmo**

In [71]:
pos = np.array([1.0, 2.0, 4.0, 8.0])

print(np.log(pos)) # ln
print(np.log2(pos)) # log₂
print(np.exp(pos)) # e^x


[0.         0.69314718 1.38629436 2.07944154]
[0. 1. 2. 3.]
[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]


**Trigonometría (argumentos en radianes)**

In [72]:
angulos = np.linspace(0, 2 * np.pi, 5) # 0, π/2, π, 3π/2, 2π

print(np.sin(angulos).round(4))
print(np.cos(angulos).round(4))

[ 0.  1.  0. -1. -0.]
[ 1.  0. -1. -0.  1.]


**clip — limitar valores a un rango**

In [73]:
datos = np.array([-10, -5, 0, 5, 10, 15, 20])
recortado = np.clip(datos, 0, 10) # valores entre 0 y 10
print(recortado)

[ 0  0  0  5 10 10 10]


**maximum / minimum elemento a elemento**

In [74]:
a = np.array([3, 1, 7, 2])
b = np.array([4, 5, 2, 8])
print(np.maximum(a, b))
print(np.minimum(a, b))

[4 5 7 8]
[3 1 2 2]


***Estadística y Reducciones***

In [75]:
M = np.array([[4, 7, 2, 8],
[3, 11, 5, 1],
[6, 9, 0, 4]])


**Reducción global (todos los ejes)**

In [76]:
print(M.sum())
print(M.mean())
print(M.max())
print(M.min())

60
5.0
11
0


**Reducción por eje**

In [77]:
print("suma por columna: ",M.sum(axis=0))
print("suma por fila: ",M.sum(axis=1))
print("media de cada columna: ",M.mean(axis=0))
print("maximo de cada fila: ",M.max(axis=1))

suma por columna:  [13 27  7 13]
suma por fila:  [21 20 19]
media de cada columna:  [4.33333333 9.         2.33333333 4.33333333]
maximo de cada fila:  [ 8 11  9]


**argmin / argmax — índice del extremo**

In [78]:
print(M.argmin(axis=1))
print(M.argmax(axis=0))

[2 3 2]
[2 1 1 0]


**std y var**

In [79]:
print(M.std()) # desviación estándar global
print(M.var(axis=0)) # varianza de cada columna


3.1885210782848317
[1.55555556 2.66666667 4.22222222 8.22222222]


**keepdims — mantener dimensiones**

In [80]:
media = M.mean(axis=0, keepdims=True)
print(media.shape)
centrado = M - media

(1, 4)


**cumsum — suma acumulada**

In [81]:
v = np.array([1, 2, 3, 4, 5])
print(np.cumsum(v))

[ 1  3  6 10 15]


**percentile**

In [82]:
print(np.percentile(M, 25))
print(np.median(M))

2.75
4.5


***Concatenación y Apilamiento de Arrays***

In [83]:
A = np.array([[1, 2, 3],
[4, 5, 6]])
B = np.array([[7, 8, 9],
[10, 11, 12]])


**concatenate**

In [85]:
vertical = np.concatenate([A, B], axis=0)
print(vertical.shape)
horizontal = np.concatenate([A, B], axis=1)
print(horizontal.shape)

(4, 3)
(2, 6)


**vstack y hstack**

In [86]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.vstack([v1, v2]))
print(np.hstack([v1, v2]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**stack — crea nuevo eje**

In [87]:
capas = np.stack([A, B], axis=0)
print(capas.shape)


(2, 2, 3)


**split**

In [88]:
M = np.arange(1, 25).reshape(4, 6)
partes = np.split(M, 2, axis=1)
print(partes[0].shape)
print(partes[1].shape)
filas = np.vsplit(M, 4)
print(filas[0])

(4, 3)
(4, 3)
[[1 2 3 4 5 6]]


***Ordenamiento y Búsqueda***

In [89]:
v = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6])

**sort**

In [90]:
v = np.array([5, 2, 8, 1, 9, 3])
idx = np.argsort(v)
print(v[idx])

[1 2 3 5 8 9]


**Reordenar dos arrays en paralelo**

In [91]:
nombres = np.array(['Carlos','Ana','Diana','Pedro','Eva','Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])
orden = np.argsort(notas)[::-1]
print(nombres[orden])
print(notas[orden])

['Eva' 'Ana' 'Diana' 'Luis' 'Carlos' 'Pedro']
[95 92 88 78 75 61]


**np.where con 1 argumento — posiciones de True**

In [92]:
datos = np.array([0, 5, 0, 3, 0, 8])
pos = np.where(datos > 0)
print(pos)
print(datos[pos])

(array([1, 3, 5]),)
[5 3 8]


**unique**

In [93]:
colores = np.array([1, 2, 1, 3, 2, 1, 4, 3])
unicos, conteos = np.unique(colores, return_counts=True)
print(unicos)
print(conteos)

[1 2 3 4]
[3 2 2 1]
