<a href="https://colab.research.google.com/github/Dilan-D-S/Inteligencia_Artificial_Est/blob/main/Taller1/TallerNumpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller de Numpy
**Practica**
Autor: Dilan Delgado

fecha:16/04/2026

# **PRÁCTICA**
# **Módulo 1 — Estructuras de Datos Python**

**Ejercicio 1:** Crea una lista con los múltiplos de 7 entre 1 y 100 usando comprehension.

In [ ]:
multiplos = [x for x in range(1,101) if x%7 == 0]
print(multiplos)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


**Ejercicio 2:** Dado el diccionario

In [ ]:
datos = {'a':10, 'b':25, 'c':7, 'd':18}

**a)** Crea una lista con las claves cuyo valor sea mayor a 12.

In [ ]:
mayor= [x for x, i in datos.items() if i>12]
print(mayor)

['b', 'd']


**b)** Crea un nuevo diccionario con esas claves y sus valores al cuadrado.

In [ ]:
Dcuadrado= {x: i**2 for x, i in datos.items() if i>12}
print(Dcuadrado)

{'b': 625, 'd': 324}


**Ejercicio 3:** Define una función 'resumen(lista)' que retorne un diccionario con: longitud, suma, promedio, mínimo y máximo de la lista.

In [ ]:
def resumen (lista):
  return {'longitud': len(lista),
          'suma': sum(lista),
          'promedio' : sum(lista)/len(lista),
          'minimo' : min(lista),
          'maximo' : max(lista)
          }

print(resumen([1, 2, 3, 4, 5]))

{'longitud': 5, 'suma': 15, 'promedio': 3.0, 'minimo': 1, 'maximo': 5}


**Ejercicio 4:** Usa map() para aplicar la función potencia(x, 3) a la lista [1,2,3,4,5]

In [ ]:
def potencia(base,exponente=2):
  return base**exponente

lista = [1, 2, 3, 4, 5]

resultado = list(map(lambda x: potencia(x, 3), lista))
print(resultado)

[1, 8, 27, 64, 125]


# **PRACTICA**
# **Módulo 2 — Creación y Atributos de Arrays**

**Ejercicio 1:** Crea los siguientes arrays y verifica sus atributos (shape, dtype, ndim)

a) Vector con enteros del 1 al 20.

In [1]:
import numpy as np

a = np.arange(1, 21)

print("a:", a)
print("shape:", a.shape, "dtype:", a.dtype, "ndim:", a.ndim)

a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
shape: (20,) dtype: int64 ndim: 1


b) Matriz de ceros de 5 filas y 3 columnas.

In [2]:
b = np.zeros((5, 3))

print("\nb:\n", b)
print("shape:", b.shape, "dtype:", b.dtype, "ndim:", b.ndim)


b:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape: (5, 3) dtype: float64 ndim: 2


c) 10 puntos igualmente espaciados entre -1 y 1 con linspace.

In [3]:
c = np.linspace(-1, 1, 10)

print("\nc:", c)
print("shape:", c.shape, "dtype:", c.dtype, "ndim:", c.ndim)


c: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
shape: (10,) dtype: float64 ndim: 1


**Ejercicio 2:** Con np.random.seed(99) crea una matriz 4×4 de enteros entre 0 y 50.
Imprime: shape, dtype, tamaño en bytes (nbytes) y el elemento [2,3].


In [4]:
np.random.seed(99)

m = np.random.randint(0, 51, (4, 4))

print("Matriz:\n", m)
print("shape:", m.shape)
print("dtype:", m.dtype)
print("nbytes:", m.nbytes)
print("Elemento [2,3]:", m[2, 3])

Matriz:
 [[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
shape: (4, 4)
dtype: int64
nbytes: 128
Elemento [2,3]: 49


**Ejercicio 3:** ¿Cuál es la diferencia de dtype entre np.array([1,2,3]) y
np.array([1.0,2.0,3.0])? Verifica con código.


In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1.0, 2.0, 3.0])

print("arr1 dtype:", arr1.dtype)
print("arr2 dtype:", arr2.dtype)

arr1 dtype: int64
arr2 dtype: float64


**Ejercicio 4:** Crea una matriz identidad 5×5 y verifica que la suma de su diagonal
es igual a 5 (usa np.trace())

In [6]:
I = np.eye(5)

print("Matriz identidad:\n", I)
print("Suma de la diagonal:", np.trace(I))

Matriz identidad:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Suma de la diagonal: 5.0


# **PRÁCTICA**  
# **Módulo 3 — Indexing, Slicing, Reshape**


**Ejercicio 1:** Dado A = np.arange(1, 26).reshape(5, 5)

In [7]:
A = np.arange(1, 26).reshape(5, 5)
print("Matriz A:\n", A)

Matriz A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


a) Extrae la sub-matriz de las 3 últimas filas y las 3 primeras columnas.


In [8]:
sub_a = A[2:, :3]
print("Submatriz:\n", sub_a)


Submatriz:
 [[11 12 13]
 [16 17 18]
 [21 22 23]]


b) Extrae la segunda columna completa.


In [9]:
col_b = A[:, 1]
print("Segunda columna:\n", col_b)



Segunda columna:
 [ 2  7 12 17 22]


c) Extrae los elementos de los ángulos (esquinas) de la matriz.


In [10]:
esquinas = [A[0, 0], A[0, -1], A[-1, 0], A[-1, -1]]
print("Esquinas:", esquinas)


Esquinas: [np.int64(1), np.int64(5), np.int64(21), np.int64(25)]


**Ejercicio 2:** Con la misma matriz A:

a) Crea una máscara booleana para los valores mayores a 12.


In [11]:
mask = A > 12
print("Máscara:\n", mask)

Máscara:
 [[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


b) Reemplaza esos valores por -1 en una copia del array.


In [12]:
B = A.copy()
B[mask] = -1
print("Copia modificada:\n", B)


Copia modificada:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


c) Usa np.where para reemplazar impares por 0 y mantener los pares

In [13]:
C = np.where(A % 2 == 0, A, 0)
print("Pares se mantienen, impares a 0:\n", C)


Pares se mantienen, impares a 0:
 [[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]


**Ejercicio 3:** Crea un vector de 24 elementos con arange(24).
Reorganízalo en:

In [14]:
v = np.arange(24)

a) matriz 6×4

In [15]:
m_6x4 = v.reshape(6, 4)
print("6x4:\n", m_6x4)

6x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


b) tensor 2×3×4

In [16]:
t_2x3x4 = v.reshape(2, 3, 4)
print("2x3x4:\n", t_2x3x4)


2x3x4:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


c) vector fila 1×24.

In [17]:
fila = v.reshape(1, 24)
print("1x24:\n", fila)


1x24:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


**Ejercicio 4:** Demuestra la diferencia vista vs. copia: modifica un elemento
en un slice y verifica que el array original también cambia.

In [18]:
A = np.arange(1, 10).reshape(3, 3)

slice_A = A[:2, :2]

slice_A[0, 0] = 999

print("Slice modificado:\n", slice_A)
print("\nArray original (también cambia):\n", A)

Slice modificado:
 [[999   2]
 [  4   5]]

Array original (también cambia):
 [[999   2   3]
 [  4   5   6]
 [  7   8   9]]


# **PRÁCTICA**  
# **Módulo 4 — Operaciones Numéricas y Manejo de Datos**

**Ejercicio 1:** Crea una matriz 5×4 de enteros aleatorios entre 1 y 100 (seed=7).


In [19]:
np.random.seed(7)
A = np.random.randint(1, 101, (5, 4))

print("Matriz A:\n", A)

Matriz A:
 [[48 69 26 68]
 [84 24 93 58]
 [15 24 73 90]
 [43 91  9 40]
 [69 49  8 45]]


a) Calcula la media, máximo y mínimo de cada columna

In [21]:
media = A.mean(axis=0)
maximo = A.max(axis=0)
minimo = A.min(axis=0)

print("Media:", media)
print("Máximo:", maximo)
print("Mínimo:", minimo)


Media: [51.8 51.4 41.8 60.2]
Máximo: [84 91 93 90]
Mínimo: [15 24  8 40]


b) Calcula la suma acumulada de la primera fila.


In [22]:
acum = np.cumsum(A[0])
print("Suma acumulada (fila 1):", acum)

Suma acumulada (fila 1): [ 48 117 143 211]


c) Normaliza la matriz para que cada columna tenga valores entre 0 y 1.
Fórmula: (x - min_col) / (max_col - min_col)


In [23]:
A_norm = (A - minimo) / (maximo - minimo)
print("Matriz normalizada:\n", A_norm)

Matriz normalizada:
 [[0.47826087 0.67164179 0.21176471 0.56      ]
 [1.         0.         1.         0.36      ]
 [0.         0.         0.76470588 1.        ]
 [0.4057971  1.         0.01176471 0.        ]
 [0.7826087  0.37313433 0.         0.1       ]]


**Ejercicio 2:** Usando broadcasting:

a) Crea un vector fila [1,2,3,4] y un vector columna [[10],[20],[30]].


In [24]:
fila = np.array([1, 2, 3, 4])
columna = np.array([[10], [20], [30]])

b) Suma ambos vectores y explica el shape del resultado.

In [25]:
resultado = fila + columna

print("Resultado:\n", resultado)
print("Shape:", resultado.shape)

Resultado:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Shape: (3, 4)


**Ejercicio 3:** Con el array de notas y nombres del ejemplo de argsort:


In [28]:
nombres = np.array(["Ana", "Luis", "Pedro", "Marta"])
notas = np.array([70, 85, 60, 90])

promedio = notas.mean()
print("Promedio:", promedio)

Promedio: 76.25


a) ¿Cuántos estudiantes tienen nota mayor al promedio? (usa máscara booleana)


In [29]:
mask = notas > promedio
cantidad = np.sum(mask)
print("Cantidad mayor al promedio:", cantidad)

Cantidad mayor al promedio: 2


b) Imprime solo los nombres de esos estudiantes.

In [30]:
aprobados = nombres[mask]
print("Nombres:", aprobados)

Nombres: ['Luis' 'Marta']


**Ejercicio 4:** Crea dos matrices 3×4 y concaténalas vertical y horizontalmente.
Luego divide el resultado vertical en 3 partes iguales con vsplit.

In [31]:
A = np.arange(12).reshape(3, 4)
B = np.arange(12, 24).reshape(3, 4)

# Concatenación
vertical = np.vstack((A, B))
horizontal = np.hstack((A, B))

print("Vertical:\n", vertical)
print("\nHorizontal:\n", horizontal)

# Dividir en 3 partes iguales
dividido = np.vsplit(vertical, 3)

print("\nDivisiones:")
for i, d in enumerate(dividido):
    print(f"Parte {i}:\n", d)

Vertical:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Horizontal:
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

Divisiones:
Parte 0:
 [[0 1 2 3]
 [4 5 6 7]]
Parte 1:
 [[ 8  9 10 11]
 [12 13 14 15]]
Parte 2:
 [[16 17 18 19]
 [20 21 22 23]]
